wildcard achievement update lite
sedgestripe/clangen pull request #41
Opened 2024-01-16 23:04 UTC by ChibiGalaxies

Just trying to merge the code to add the 'masked' pelt to the patchwork wildcard achievement, and also add the amendment to stop a false positive wildcard from having a 'single' pattern tortie patch

2024-01-17 06:00 UTC, sedgestripe requested changes

2024-01-17 06:00 UTC, sedgestripe commented on scripts/housekeeping/version.py
just a nitpick, remove changing this file from pr

2024-01-18 18:57 UTC, ChibiGalaxies commented on scripts/housekeeping/version.py
Manually fixed my version.py and seems to have disappeared from the Pr, hoping that it's fixed!

2024-01-18 20:36 UTC, sedgestripe approved these changes
looks great!!

2024-01-18 20:36 UTC, merged